name: CI Workflow - Check for submitForm()

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Jobs to run
jobs:
  check-submit-form:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Check if submitForm() exists in script.js
      - name: Check for submitForm()
        run: |
          if grep -q "function submitForm()" script.js; then
            echo "submitForm() function found in script.js."
          else
            echo "::error::submitForm() function not found in script.js!"
            exit 1 # Fail the workflow
          fi