name: CI/CD Pipeline for script.js

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Jobs to run
jobs:
  validate-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Validate script.js for invalid variable names
      - name: Validate script.js
        id: validate-script
        run: |
          echo "Checking script.js for invalid variable names..."
          if grep -E '\b[0-9]+\w*\b|\W+\w*\b' script.js; then
            echo "::error::Invalid variable names found in script.js! Variables cannot start with numbers or contain special characters."
            exit 1 # Fail the workflow
          else
            echo "No invalid variable names found in script.js."
          fi