name: Deploy to GitHub Pages

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Jobs to run
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Ensure gh-pages branch exists
      - name: Ensure gh-pages branch exists
        run: |
          git fetch origin
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
          fi

      # Step 3: Deploy to GitHub Pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Deploy the root directory (or specify the folder containing your HTML/CSS/JS files)
